package period2011

import "github.com/mzdyhrave/legaliosgo/internal/providers/period2010"

const (
	SALARY_VERSION_CODE int16 = 2011
	SALARY_WORKING_SHIFT_WEEK = period2010.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2010.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = period2010.SALARY_MIN_MONTHLY_WAGE
	SALARY_MIN_HOURLY_WAGE = period2010.SALARY_MIN_HOURLY_WAGE
)

