package period2011

import "github.com/mzdyhrave/legaliosgo/internal/providers/period2010"

const (
	HEALTH_VERSION_CODE int16 = 2011
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = 1781280
	HEALTH_LIM_MONTHLY_STATE = period2010.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = period2010.HEALTH_LIM_MONTHLY_DIS50
	HEALTH_FACTOR_COMPOUND float64 = period2010.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE float64 = period2010.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2010.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2010.HEALTH_MARGIN_INCOME_AGR
)

