package period2015

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2014"
)

const (
	HEALTH_VERSION_CODE int16 = 2015
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2014.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2014.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = period2014.VAR07_HEALTH_LIM_MONTHLY_DIS50
	HEALTH_FACTOR_COMPOUND = period2014.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2014.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2014.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2014.HEALTH_MARGIN_INCOME_AGR
)

