package period2015

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2014"
)

const (
	TAXING_VERSION_CODE int16 = 2015
	TAXING_ALLOWANCE_PAYER = period2014.TAXING_ALLOWANCE_PAYER
	TAXING_ALLOWANCE_DISAB_1ST = period2014.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2014.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2014.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2014.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = period2014.TAXING_ALLOWANCE_CHILD_1ST
	TAXING_ALLOWANCE_CHILD_2ND = 1317
	TAXING_ALLOWANCE_CHILD_3RD = 1417
	TAXING_FACTOR_ADVANCES float64 = period2014.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2014.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLIDARY float64 = period2014.TAXING_FACTOR_SOLIDARY
	TAXING_FACTOR_TAXRATE2 float64 = period2014.TAXING_FACTOR_TAXRATE2
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2014.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = period2014.TAXING_MAX_AMOUNT_OF_TAXBONUS
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2014.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2014.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLIDARY = (4 * 26611)
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = period2014.TAXING_MARGIN_INCOME_OF_TAXRATE2
	TAXING_MARGIN_INCOME_OF_WHT_EMP = period2014.TAXING_MARGIN_INCOME_OF_WHT_EMP
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2014.TAXING_MARGIN_INCOME_OF_WHT_AGR
)

