package period2015

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2014"
)

const (
	SALARY_VERSION_CODE int16 = 2015
	SALARY_WORKING_SHIFT_WEEK = period2014.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2014.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 9200
	SALARY_MIN_HOURLY_WAGE = 5500
)

