package period2019

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2018"
)

const (
	SOCIAL_VERSION_CODE int16 = 2019
	SOCIAL_MAX_ANNUALS_BASIS = 1569552
	SOCIAL_FACTOR_EMPLOYER float64 = period2018.SOCIAL_FACTOR_EMPLOYER
	SOCIAL_FACTOR_EMPLOYER_HIGHER float64 = period2018.SOCIAL_FACTOR_EMPLOYER_HIGHER
	SOCIAL_FACTOR_EMPLOYEE float64 = period2018.SOCIAL_FACTOR_EMPLOYEE
	SOCIAL_FACTOR_EMPLOYEE_REDUCE float64 = period2018.SOCIAL_FACTOR_EMPLOYEE_REDUCE
	SOCIAL_FACTOR_EMPLOYEE_GARANT float64 = period2018.SOCIAL_FACTOR_EMPLOYEE_GARANT
	SOCIAL_MARGIN_INCOME_EMP = 3000
	SOCIAL_MARGIN_INCOME_AGR = period2018.SOCIAL_MARGIN_INCOME_AGR

	VAR07_SOCIAL_FACTOR_EMPLOYER float64 = 24.8
)

