package period2019

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2018"
)

const (
	SALARY_VERSION_CODE int16 = 2019
	SALARY_WORKING_SHIFT_WEEK = period2018.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2018.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 13350
	SALARY_MIN_HOURLY_WAGE = 7980
)

