package period2013

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2012"
)

const (
	SALARY_VERSION_CODE int16 = 2013
	SALARY_WORKING_SHIFT_WEEK = period2012.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2012.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = period2012.SALARY_MIN_MONTHLY_WAGE
	SALARY_MIN_HOURLY_WAGE = period2012.SALARY_MIN_HOURLY_WAGE

	VAR08_SALARY_MIN_MONTHLY_WAGE = 8500
	VAR08_SALARY_MIN_HOURLY_WAGE = 5060

)

