package period2013

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2012"
)

const (
	SOCIAL_VERSION_CODE int16 = 2013
	SOCIAL_MAX_ANNUALS_BASIS = 1242432
	SOCIAL_FACTOR_EMPLOYER float64 = period2012.SOCIAL_FACTOR_EMPLOYER
	SOCIAL_FACTOR_EMPLOYER_HIGHER float64 = period2012.SOCIAL_FACTOR_EMPLOYER_HIGHER
	SOCIAL_FACTOR_EMPLOYEE float64 = period2012.SOCIAL_FACTOR_EMPLOYEE
	SOCIAL_FACTOR_EMPLOYEE_REDUCE float64 = period2012.SOCIAL_FACTOR_EMPLOYEE_REDUCE
	SOCIAL_FACTOR_EMPLOYEE_GARANT float64 = period2012.SOCIAL_FACTOR_EMPLOYEE_GARANT
	SOCIAL_MARGIN_INCOME_EMP = period2012.SOCIAL_MARGIN_INCOME_EMP
	SOCIAL_MARGIN_INCOME_AGR = period2012.SOCIAL_MARGIN_INCOME_AGR

	VAR02_SOCIAL_FACTOR_EMPLOYEE_REDUCE float64 = 3
	VAR02_SOCIAL_FACTOR_EMPLOYEE_GARANT float64 = 5

)

