package period2020

import (
	"github.com/mzdyhrave/payrollgo-legalios/internal/providers/period2019"
)

const (
	TAXING_VERSION_CODE int16 = 2020
	TAXING_ALLOWANCE_PAYER = period2019.TAXING_ALLOWANCE_PAYER
	TAXING_ALLOWANCE_DISAB_1ST = period2019.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2019.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2019.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2019.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = period2019.TAXING_ALLOWANCE_CHILD_1ST
	TAXING_ALLOWANCE_CHILD_2ND = period2019.TAXING_ALLOWANCE_CHILD_2ND
	TAXING_ALLOWANCE_CHILD_3RD = period2019.TAXING_ALLOWANCE_CHILD_3RD
	TAXING_FACTOR_ADVANCES float64 = period2019.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2019.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLITARY float64 = period2019.TAXING_FACTOR_SOLITARY
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2019.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = period2019.TAXING_MAX_AMOUNT_OF_TAXBONUS
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2019.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2019.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLITARY = (4 * 34835)
	TAXING_MARGIN_INCOME_OF_WHT_EMP = period2019.VAR05_TAXING_MARGIN_INCOME_OF_WHT_EMP
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2019.TAXING_MARGIN_INCOME_OF_WHT_AGR
)

