package period2020

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2019"
)

const (
	HEALTH_VERSION_CODE int16 = 2020
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2019.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2019.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = 7903
	HEALTH_FACTOR_COMPOUND = period2019.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2019.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2019.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2019.HEALTH_MARGIN_INCOME_AGR

	VAR06_HEALTH_LIM_MONTHLY_DIS50 = 11607
)

