package period2020

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2019"
)

const (
	SALARY_VERSION_CODE int16 = 2020
	SALARY_WORKING_SHIFT_WEEK = period2019.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2019.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 14600
	SALARY_MIN_HOURLY_WAGE = 8730
)

