package period2022

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2021"
)

const (
	TAXING_VERSION_CODE int16 = 2022
	TAXING_ALLOWANCE_PAYER = 2570
	TAXING_ALLOWANCE_DISAB_1ST = period2021.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2021.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2021.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2021.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = period2021.TAXING_ALLOWANCE_CHILD_1ST
	TAXING_ALLOWANCE_CHILD_2ND = period2021.TAXING_SETTLEMENT_CHILD_2ND
	TAXING_ALLOWANCE_CHILD_3RD = period2021.TAXING_SETTLEMENT_CHILD_3RD
	TAXING_FACTOR_ADVANCES float64 = period2021.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2021.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLIDARY float64 = period2021.TAXING_FACTOR_SOLIDARY
	TAXING_FACTOR_TAXRATE2 float64 = period2021.TAXING_FACTOR_TAXRATE2
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2021.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = 0
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2021.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2021.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLIDARY = period2021.TAXING_MARGIN_INCOME_OF_SOLIDARY
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = (4 * 38911)
	TAXING_MARGIN_INCOME_OF_WHT_EMP = period2021.TAXING_MARGIN_INCOME_OF_WHT_EMP
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2021.TAXING_MARGIN_INCOME_OF_WHT_AGR
)

