package period2022

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2021"
)

const (
	SALARY_VERSION_CODE int16 = 2022
	SALARY_WORKING_SHIFT_WEEK = period2021.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2021.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 16200
	SALARY_MIN_HOURLY_WAGE = 9640
)

