package period2021

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2020"
)

const (
	TAXING_VERSION_CODE int16 = 2021
	TAXING_ALLOWANCE_PAYER = 2320
	TAXING_ALLOWANCE_DISAB_1ST = period2020.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2020.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2020.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2020.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = period2020.TAXING_ALLOWANCE_CHILD_1ST
	TAXING_ALLOWANCE_CHILD_2ND = period2020.TAXING_ALLOWANCE_CHILD_2ND
	TAXING_ALLOWANCE_CHILD_3RD = period2020.TAXING_ALLOWANCE_CHILD_3RD
	TAXING_SETTLEMENT_CHILD_2ND = 1860
	TAXING_SETTLEMENT_CHILD_3RD = 2320
	TAXING_FACTOR_ADVANCES float64 = period2020.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2020.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLIDARY float64 = 0
	TAXING_FACTOR_TAXRATE2 float64 = 23
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2020.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = period2020.TAXING_MAX_AMOUNT_OF_TAXBONUS
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2020.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2020.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLIDARY = 0
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = (4 * 35441)
	TAXING_MARGIN_INCOME_OF_WHT_EMP = 3500
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2020.TAXING_MARGIN_INCOME_OF_WHT_AGR
)

