package period2021

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2020"
)

const (
	HEALTH_VERSION_CODE int16 = 2021
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2020.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2020.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = 13088
	HEALTH_FACTOR_COMPOUND = period2020.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2020.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = 3500
	HEALTH_MARGIN_INCOME_AGR = period2020.HEALTH_MARGIN_INCOME_AGR
)

