package period2021

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2020"
)

const (
	SALARY_VERSION_CODE int16 = 2021
	SALARY_WORKING_SHIFT_WEEK = period2020.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2020.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 15200
	SALARY_MIN_HOURLY_WAGE = 9050
)

