package period2014

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2013"
)

const (
	HEALTH_VERSION_CODE int16 = 2014
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2013.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2013.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = period2013.VAR11_HEALTH_LIM_MONTHLY_DIS50
	HEALTH_FACTOR_COMPOUND = period2013.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2013.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2013.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2013.HEALTH_MARGIN_INCOME_AGR

	VAR07_HEALTH_LIM_MONTHLY_DIS50 = 6259
)

