package period2014

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2013"
)

const (
	SOCIAL_VERSION_CODE int16 = 2014
	SOCIAL_MAX_ANNUALS_BASIS = 1245216
	SOCIAL_FACTOR_EMPLOYER float64 = period2013.SOCIAL_FACTOR_EMPLOYER
	SOCIAL_FACTOR_EMPLOYER_HIGHER float64 = period2013.SOCIAL_FACTOR_EMPLOYER_HIGHER
	SOCIAL_FACTOR_EMPLOYEE float64 = period2013.SOCIAL_FACTOR_EMPLOYEE
	SOCIAL_FACTOR_EMPLOYEE_REDUCE float64 = period2013.VAR02_SOCIAL_FACTOR_EMPLOYEE_REDUCE
	SOCIAL_FACTOR_EMPLOYEE_GARANT float64 = period2013.VAR02_SOCIAL_FACTOR_EMPLOYEE_GARANT
	SOCIAL_MARGIN_INCOME_EMP = period2013.SOCIAL_MARGIN_INCOME_EMP
	SOCIAL_MARGIN_INCOME_AGR = period2013.SOCIAL_MARGIN_INCOME_AGR
)

