package period2014

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2013"
)

const (
	SALARY_VERSION_CODE int16 = 2014
	SALARY_WORKING_SHIFT_WEEK = period2013.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2013.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = period2013.VAR08_SALARY_MIN_MONTHLY_WAGE
	SALARY_MIN_HOURLY_WAGE = period2013.VAR08_SALARY_MIN_HOURLY_WAGE
)

