package period2018

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2017"
)

const (
	HEALTH_VERSION_CODE int16 = 2018
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2017.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2017.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = 7177
	HEALTH_FACTOR_COMPOUND = period2017.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2017.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2017.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2017.HEALTH_MARGIN_INCOME_AGR
)

