package period2018

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2017"
)

const (
	SALARY_VERSION_CODE int16 = 2018
	SALARY_WORKING_SHIFT_WEEK = period2017.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2017.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 12200
	SALARY_MIN_HOURLY_WAGE = 7320
)

