package period2012

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2011"
)

const (
	SOCIAL_VERSION_CODE int16 = 2012
	SOCIAL_MAX_ANNUALS_BASIS = 1206576
	SOCIAL_FACTOR_EMPLOYER float64 = period2011.SOCIAL_FACTOR_EMPLOYER
	SOCIAL_FACTOR_EMPLOYER_HIGHER float64 = period2011.SOCIAL_FACTOR_EMPLOYER_HIGHER
	SOCIAL_FACTOR_EMPLOYEE float64 = period2011.SOCIAL_FACTOR_EMPLOYEE
	SOCIAL_FACTOR_EMPLOYEE_REDUCE float64 = period2011.SOCIAL_FACTOR_EMPLOYEE_REDUCE
	SOCIAL_FACTOR_EMPLOYEE_GARANT float64 = period2011.SOCIAL_FACTOR_EMPLOYEE_GARANT
	SOCIAL_MARGIN_INCOME_EMP = 2500
	SOCIAL_MARGIN_INCOME_AGR = 10001
)

