package period2012

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2011"
)

const (
	TAXING_VERSION_CODE int16 = 2012
	TAXING_ALLOWANCE_PAYER = 2070
	TAXING_ALLOWANCE_DISAB_1ST = period2011.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2011.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2011.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2011.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = 1117
	TAXING_ALLOWANCE_CHILD_2ND = 1117
	TAXING_ALLOWANCE_CHILD_3RD = 1117
	TAXING_FACTOR_ADVANCES float64 = period2011.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2011.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLIDARY float64 = period2011.TAXING_FACTOR_SOLIDARY
	TAXING_FACTOR_TAXRATE2 float64 = period2011.TAXING_FACTOR_TAXRATE2
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2011.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = 5025
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2011.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2011.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLIDARY = period2011.TAXING_MARGIN_INCOME_OF_SOLIDARY
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = period2011.TAXING_MARGIN_INCOME_OF_TAXRATE2
	TAXING_MARGIN_INCOME_OF_WHT_EMP = period2011.TAXING_MARGIN_INCOME_OF_WHT_EMP
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2011.TAXING_MARGIN_INCOME_OF_WHT_AGR
)

