package period2012

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2011"
)

const (
	HEALTH_VERSION_CODE int16 = 2012
	HEALTH_MIN_MONTHLY_BASIS = period2011.HEALTH_MIN_MONTHLY_BASIS
	HEALTH_MAX_ANNUALS_BASIS = 1809864
	HEALTH_LIM_MONTHLY_STATE = period2011.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = period2011.HEALTH_LIM_MONTHLY_DIS50
	HEALTH_FACTOR_COMPOUND = period2011.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2011.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = 2500
	HEALTH_MARGIN_INCOME_AGR = 10001
)

