package period2016

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2015"
)

const (
	SALARY_VERSION_CODE int16 = 2016
	SALARY_WORKING_SHIFT_WEEK = period2015.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2015.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 9900
	SALARY_MIN_HOURLY_WAGE = 5870
)

