package period2016

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2015"
)

const (
	HEALTH_VERSION_CODE int16 = 2016
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = period2015.HEALTH_MAX_ANNUALS_BASIS
	HEALTH_LIM_MONTHLY_STATE = period2015.HEALTH_LIM_MONTHLY_STATE
	HEALTH_LIM_MONTHLY_DIS50 = 6444
	HEALTH_FACTOR_COMPOUND = period2015.HEALTH_FACTOR_COMPOUND
	HEALTH_FACTOR_EMPLOYEE = period2015.HEALTH_FACTOR_EMPLOYEE
	HEALTH_MARGIN_INCOME_EMP = period2015.HEALTH_MARGIN_INCOME_EMP
	HEALTH_MARGIN_INCOME_AGR = period2015.HEALTH_MARGIN_INCOME_AGR
)

