package period2017

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2016"
)

const (
	SALARY_VERSION_CODE int16 = 2017
	SALARY_WORKING_SHIFT_WEEK = period2016.SALARY_WORKING_SHIFT_WEEK
	SALARY_WORKING_SHIFT_TIME = period2016.SALARY_WORKING_SHIFT_TIME
	SALARY_MIN_MONTHLY_WAGE = 11000
	SALARY_MIN_HOURLY_WAGE = 6600
)

