package period2017

import (
	"github.com/mzdyhrave/legaliosgo/internal/providers/period2016"
)

const (
	TAXING_VERSION_CODE int16 = 2017
	TAXING_ALLOWANCE_PAYER = period2016.TAXING_ALLOWANCE_PAYER
	TAXING_ALLOWANCE_DISAB_1ST = period2016.TAXING_ALLOWANCE_DISAB_1ST
	TAXING_ALLOWANCE_DISAB_2ND = period2016.TAXING_ALLOWANCE_DISAB_2ND
	TAXING_ALLOWANCE_DISAB_3RD = period2016.TAXING_ALLOWANCE_DISAB_3RD
	TAXING_ALLOWANCE_STUDY = period2016.TAXING_ALLOWANCE_STUDY
	TAXING_ALLOWANCE_CHILD_1ST = period2016.TAXING_ALLOWANCE_CHILD_1ST
	TAXING_ALLOWANCE_CHILD_2ND = period2016.VAR05_TAXING_ALLOWANCE_CHILD_2ND
	TAXING_ALLOWANCE_CHILD_3RD = period2016.VAR05_TAXING_ALLOWANCE_CHILD_3RD
	TAXING_FACTOR_ADVANCES float64 = period2016.TAXING_FACTOR_ADVANCES
	TAXING_FACTOR_WITHHOLD float64 = period2016.TAXING_FACTOR_WITHHOLD
	TAXING_FACTOR_SOLIDARY float64 = period2016.TAXING_FACTOR_SOLIDARY
	TAXING_FACTOR_TAXRATE2 float64 = period2016.TAXING_FACTOR_TAXRATE2
	TAXING_MIN_AMOUNT_OF_TAXBONUS = period2016.TAXING_MIN_AMOUNT_OF_TAXBONUS
	TAXING_MAX_AMOUNT_OF_TAXBONUS = period2016.TAXING_MAX_AMOUNT_OF_TAXBONUS
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = period2016.TAXING_MARGIN_INCOME_OF_ROUNDING
	TAXING_MARGIN_INCOME_OF_WITHHOLD = period2016.TAXING_MARGIN_INCOME_OF_WITHHOLD
	TAXING_MARGIN_INCOME_OF_SOLIDARY = (4 * 28232)
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = period2016.TAXING_MARGIN_INCOME_OF_TAXRATE2
	TAXING_MARGIN_INCOME_OF_WHT_EMP = period2016.TAXING_MARGIN_INCOME_OF_WHT_EMP
	TAXING_MARGIN_INCOME_OF_WHT_AGR = period2016.TAXING_MARGIN_INCOME_OF_WHT_AGR

	VAR07_TAXING_ALLOWANCE_CHILD_2ND = 1617
	VAR07_TAXING_ALLOWANCE_CHILD_3RD = 2017
)

