package period2010

const (
	TAXING_VERSION_CODE int16 = 2010
	TAXING_ALLOWANCE_PAYER = 2070
	TAXING_ALLOWANCE_DISAB_1ST = 210
	TAXING_ALLOWANCE_DISAB_2ND = 420
	TAXING_ALLOWANCE_DISAB_3RD = 1345
	TAXING_ALLOWANCE_STUDY = 335
	TAXING_ALLOWANCE_CHILD_1ST = 967
	TAXING_ALLOWANCE_CHILD_2ND = 967
	TAXING_ALLOWANCE_CHILD_3RD = 967
	TAXING_FACTOR_ADVANCES float64 = 15
	TAXING_FACTOR_WITHHOLD float64 = 15
	TAXING_FACTOR_SOLIDARY float64 = 0
	TAXING_FACTOR_TAXRATE2 float64 = 0
	TAXING_MIN_AMOUNT_OF_TAXBONUS = 50
	TAXING_MAX_AMOUNT_OF_TAXBONUS = 4350
	TAXING_MARGIN_INCOME_OF_TAXBONUS = (SALARY_MIN_MONTHLY_WAGE / 2)
	TAXING_MARGIN_INCOME_OF_ROUNDING = 100
	TAXING_MARGIN_INCOME_OF_WITHHOLD = 5000
	TAXING_MARGIN_INCOME_OF_SOLIDARY = 0
	TAXING_MARGIN_INCOME_OF_TAXRATE2 = 0
	TAXING_MARGIN_INCOME_OF_WHT_EMP = 0
	TAXING_MARGIN_INCOME_OF_WHT_AGR = 0
)

