package period2010

const (
	HEALTH_VERSION_CODE int16 = 2010
	HEALTH_MIN_MONTHLY_BASIS = SALARY_MIN_MONTHLY_WAGE
	HEALTH_MAX_ANNUALS_BASIS = 1707048
	HEALTH_LIM_MONTHLY_STATE = 0
	HEALTH_LIM_MONTHLY_DIS50 = 5355
	HEALTH_FACTOR_COMPOUND float64 = 13.5
	HEALTH_FACTOR_EMPLOYEE float64 = 3
	HEALTH_MARGIN_INCOME_EMP = 2000
	HEALTH_MARGIN_INCOME_AGR = HEALTH_MARGIN_INCOME_EMP
)

